version: "3.9"
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: on-failure
    volumes:
      - ../data:/var/lib/mongodb
    ports:
      - "27017:27017"

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - "3306:3306"

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    image: eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  event-service:
    image: event:latest
    container_name: event
    depends_on:
      - db
      - eureka-server
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
    ports:
      - "8085:8085"
    restart: on-failure

  market-service:
    image: market:latest
    container_name: market
    depends_on:
      - db
      - eureka-server
    ports:
      - "8086:8086"
    restart: on-failure

  gateway:
    image: gateway:latest
    container_name: gateway
    depends_on:
      - event-service
      - market-service
    ports:
      - "8087:8087"
    restart: on-failure

  authdb:
    image: postgres:16.2
    container_name: authdb
    volumes:
      - ./auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  auth-service:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: auth-service
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://authdb/authdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - authdb
